#!/usr/bin/env python 
#-*- coding:utf-8 -*- 

import sys
from lib import options

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print 'Usage: ./holmes-admin [insert|remove|get] [streams|entity-types|users] <options>'
	print 'OPTIONS:'
	print '   [users] <from-file|from-ldap>'
	sys.exit(0)
    elif len(sys.argv) == 3:
	do_evaluate_option = options.options[sys.argv[1]][sys.argv[2]]
    elif len(sys.argv) == 4:
	do_evaluate_option = options.options[sys.argv[1]][sys.argv[2]][sys.argv[3]]
    else:
	print 'Invalid number of arguments'
	sys.exit(-1)
    do_evaluate_option()
    sys.exit(0)
